# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('vote', models.FloatField()),
                ('fanta_vote', models.FloatField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('real_team', models.CharField(max_length=3)),
                ('role', models.CharField(max_length=25)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
